### PR TITLE
Delete old rules

### PR DESCRIPTION
**Pull request by shawn320**
# Description

[#28] https://taiga.dts-stn.com/project/pond-dts-eligibility-engine/task/28?kanban-status=98

Remove Newzealand's rules and tests.

### CODE REVIEW

**Comment by P0NDER0SA** [comment]
Looks like the tests are failing now because of this... try running them locally before pushing up the branch, could save you some headaches :)

**Comment by P0NDER0SA** [comment]
@shawn320 see comment above... never tagged ya

**Review by MarcoGoC — APPROVED** [review]
builds and test run locally

**Comment by MarcoGoC** [comment]
we should remove all the __pycache__ folders and files before pushing

**Review by MikeBungay — APPROVED** [review]
looks good

**Pull request merged**
