### PR TITLE
Added CERB Benefit

### PR DESCRIPTION
**Pull request by MikeBungay**
Implemented the CERB Benefit

Added the Lost all Income
Moved Tom's lost some income changes into the lost all income and applied the naming convention.  
Added the Gross income over 5K
Added Test cases for lost all, lost  some and Gross income over 5K

### CODE REVIEW

**Comment by MikeBungay** [comment]
please review

**Review by shawn320 — APPROVED** [review]
nice work! thank you

**Review by MarcoGoC — APPROVED** [review]
looks good

**Review by shewood — CHANGES_REQUESTED** [review]
For the makefile, can you remove the specific test?

**Review by shewood — APPROVED** [review]

**Pull request merged**
